### ISSUE TITLE
prepare_data.sh permission deny

### ISSUE THREAD

**Issue by zhyjiang** [mgholamikn/AdaptPose#2]
Hi, thanks for your awesome work. It seems like there are permission issues in prepare_data.sh links. 

```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=19YmZvcEbGwAcWgmO0JSVCMxxcGmKxMfE 
```

**Comment by zhyjiang** [comment]
I've tried the browser for downloading, but I still get the permission problem (403 error).
<img width="1066" alt="Screen Shot 2022-09-21 at 18 01 11" src="https://user-images.githubusercontent.com/12051776/191635954-04bee3e3-e3bb-4824-8689-23db998bd4b9.png">

**Comment by mgholamikn** [comment]
Could you please try this [link](https://drive.google.com/drive/folders/1HrYFQhWmnd9q7u9wEATKr_BHFzRNWDyk?usp=sharing)

**Comment by zhyjiang** [comment]
Thanks. I can use that link.
