### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by daebong** [mgholamikn/AdaptPose#3]
Could you upload requirements.txt? Thanks.

**Comment by mgholamikn** [comment]
Done!

**Comment by GloryyrolG** [comment]
> Done!

Hi @mgholamikn @bastianwandt, may I ask how I can get these @ file://? Or could you help provide a corresponding conda .yml?

https://github.com/mgholamikn/AdaptPose/blob/849edfa7b1f890d75af3cb42388cd89c52234de0/requirements.txt#L10
